/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.xbup.jaguif.viewer.page.gui;

import java.util.Optional;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JPopupMenu;
import javax.swing.table.TableColumn;
import org.exbin.jaguif.App;
import org.exbin.xbup.jaguif.document.XbupTreeDocument;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.xbup.core.block.XBTBlock;

/**
 * Child list table panel.
 */
@ParametersAreNonnullByDefault
public class XBBlockTablePanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(XBBlockTablePanel.class);

    private XBBlockTableModel blockTableModel = new XBBlockTableModel();
    private XBBlockNameTableCellRenderer blockNameTableCellRenderer = new XBBlockNameTableCellRenderer();

    public XBBlockTablePanel() {
        initComponents();

        init();
    }

    private void init() {
        table.setModel(blockTableModel);
        TableColumn nameColumn = table.getColumnModel().getColumn(0);
        nameColumn.setCellRenderer(blockNameTableCellRenderer);
        // TODO
        /* table.getSelectionModel().addListSelectionListener((e) -> {
            notifyItemSelectionChanged(getSelectedItem().orElse(null));
        }); */
    }

    public void setTreeDocument(XbupTreeDocument treeDocument) {
        blockTableModel.setTreeDocument(treeDocument);
        blockNameTableCellRenderer.setTreeDocument(treeDocument);

    }

    public void setBlock(@Nullable XBTBlock block) {
        blockTableModel.setBlock(block);
        blockTableModel.fireTableDataChanged();
        if (block != null) {
            table.setRowSelectionInterval(0, 0);
        }
    }

    public void setPopupMenu(JPopupMenu popupMenu) {
        table.setComponentPopupMenu(popupMenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tableScrollPane.setViewportView(table);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    @Nonnull
    public Optional<XBTBlock> getSelectedItem() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            return Optional.empty();
        }

        return Optional.ofNullable(blockTableModel.getRowAt(selectedRow));
    }
}
