#!/bin/sh
git mv modules/exbin-xbup-service/src/test/java/org/exbin/framework modules/exbin-xbup-service/src/test/java/org/exbin/jaguif
git mv modules/exbin-xbup-service/src/main/java/org/exbin/framework modules/exbin-xbup-service/src/main/java/org/exbin/jaguif
git mv modules/exbin-xbup-service/src/main/resources/org/exbin/framework modules/exbin-xbup-service/src/main/resources/org/exbin/jaguif
git mv modules/exbin-client-api/src/main/java/org/exbin/framework modules/exbin-client-api/src/main/java/org/exbin/jaguif
git mv modules/exbin-service-data/src/main/java/org/exbin/framework modules/exbin-service-data/src/main/java/org/exbin/jaguif
git mv modules/exbin-service-data/src/main/resources/org/exbin/framework modules/exbin-service-data/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-wave/src/test/java/org/exbin/framework modules/exbin-editor-wave/src/test/java/org/exbin/jaguif
git mv modules/exbin-editor-wave/src/main/java/org/exbin/framework modules/exbin-editor-wave/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-wave/src/main/resources/org/exbin/framework modules/exbin-editor-wave/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-xbup-wave/src/main/java/org/exbin/framework modules/exbin-editor-xbup-wave/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-xbup-wave/src/main/resources/org/exbin/framework modules/exbin-editor-xbup-wave/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-picture/src/test/java/org/exbin/framework modules/exbin-editor-picture/src/test/java/org/exbin/jaguif
git mv modules/exbin-editor-picture/src/main/java/org/exbin/framework modules/exbin-editor-picture/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-picture/src/main/resources/org/exbin/framework modules/exbin-editor-picture/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-xbup/src/test/java/org/exbin/framework modules/exbin-editor-xbup/src/test/java/org/exbin/jaguif
git mv modules/exbin-editor-xbup/src/main/java/org/exbin/framework modules/exbin-editor-xbup/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-xbup/src/main/resources/org/exbin/framework modules/exbin-editor-xbup/src/main/resources/org/exbin/jaguif
git mv modules/exbin-client/src/test/java/org/exbin/framework modules/exbin-client/src/test/java/org/exbin/jaguif
git mv modules/exbin-client/src/main/java/org/exbin/framework modules/exbin-client/src/main/java/org/exbin/jaguif
git mv modules/exbin-client/src/main/resources/org/exbin/framework modules/exbin-client/src/main/resources/org/exbin/jaguif
git mv modules/exbin-data-api/src/main/java/org/exbin/framework modules/exbin-data-api/src/main/java/org/exbin/jaguif
git mv modules/exbin-xbup-examples/src/main/java/org/exbin/framework modules/exbin-xbup-examples/src/main/java/org/exbin/jaguif
git mv modules/exbin-xbup-examples/src/main/resources/org/exbin/framework modules/exbin-xbup-examples/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-xbup-picture/src/main/java/org/exbin/framework modules/exbin-editor-xbup-picture/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-xbup-picture/src/main/resources/org/exbin/framework modules/exbin-editor-xbup-picture/src/main/resources/org/exbin/jaguif
git mv modules/exbin-viewer-xbup/src/test/java/org/exbin/framework modules/exbin-viewer-xbup/src/test/java/org/exbin/jaguif
git mv modules/exbin-viewer-xbup/src/main/java/org/exbin/framework modules/exbin-viewer-xbup/src/main/java/org/exbin/jaguif
git mv modules/exbin-viewer-xbup/src/main/resources/org/exbin/framework modules/exbin-viewer-xbup/src/main/resources/org/exbin/jaguif
git mv modules/exbin-xbup-catalog/src/test/java/org/exbin/framework modules/exbin-xbup-catalog/src/test/java/org/exbin/jaguif
git mv modules/exbin-xbup-catalog/src/main/java/org/exbin/framework modules/exbin-xbup-catalog/src/main/java/org/exbin/jaguif
git mv modules/exbin-xbup-catalog/src/main/resources/org/exbin/framework modules/exbin-xbup-catalog/src/main/resources/org/exbin/jaguif
git mv modules/exbin-data/src/test/java/org/exbin/framework modules/exbin-data/src/test/java/org/exbin/jaguif
git mv modules/exbin-data/src/main/java/org/exbin/framework modules/exbin-data/src/main/java/org/exbin/jaguif
git mv modules/exbin-data/src/main/resources/org/exbin/framework modules/exbin-data/src/main/resources/org/exbin/jaguif
git mv modules/exbin-editor-xbup-text/src/main/java/org/exbin/framework modules/exbin-editor-xbup-text/src/main/java/org/exbin/jaguif
git mv modules/exbin-editor-xbup-text/src/main/resources/org/exbin/framework modules/exbin-editor-xbup-text/src/main/resources/org/exbin/jaguif
