/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.xbup.catalog.item.file.gui;

import java.awt.BorderLayout;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;
import javax.swing.event.ListSelectionListener;
import org.exbin.framework.App;
import org.exbin.framework.component.api.action.ActionsProvider;
import org.exbin.framework.component.gui.ToolBarSidePanel;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.xbup.core.catalog.XBACatalog;
import org.exbin.xbup.core.catalog.base.XBCNode;
import org.exbin.xbup.core.catalog.base.XBCXFile;
import org.exbin.xbup.core.catalog.base.service.XBCXFileService;

/**
 * Catalog item files edit panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class CatalogItemEditFilesPanel extends javax.swing.JPanel {

    private XBACatalog catalog;
    private XBCXFileService fileService;
    private final CatalogFilesTableModel filesModel;
    private XBCNode currentNode;
    private final ToolBarSidePanel toolBarPanel = new ToolBarSidePanel();

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(CatalogItemEditFilesPanel.class);

    public CatalogItemEditFilesPanel() {
        filesModel = new CatalogFilesTableModel();

        initComponents();
        
        toolBarPanel.setToolBarPosition(ToolBarSidePanel.ToolBarPosition.RIGHT);
        toolBarPanel.add(catalogFilesListScrollPane, BorderLayout.CENTER);
        add(toolBarPanel, BorderLayout.CENTER);
    }

    public void addFileActions(ActionsProvider actionsProvider) {
        toolBarPanel.addActions(actionsProvider);
    }

    @Nonnull
    public CatalogFilesTableModel getFilesModel() {
        return filesModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogFilesListScrollPane = new javax.swing.JScrollPane();
        catalogFilesListTable = new javax.swing.JTable();

        catalogFilesListScrollPane.setName("catalogFilesListScrollPane"); // NOI18N

        catalogFilesListTable.setModel(filesModel);
        catalogFilesListTable.setName("catalogFilesListTable"); // NOI18N
        catalogFilesListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        catalogFilesListScrollPane.setViewportView(catalogFilesListTable);

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    public void setNode(XBCNode node) {
        currentNode = node;
        filesModel.setNode(node);
        catalogFilesListTable.revalidate();
    }

    @Nullable
    public XBCXFile getSelectedFile() {
        int selectedRow = catalogFilesListTable.getSelectedRow();
        if (selectedRow >= 0) {
            return filesModel.getItem(selectedRow);
        }
        return null;
    }

    public int getSelectedIndex() {
        return catalogFilesListTable.getSelectedRow();
    }
    
    @Nonnull
    public JToolBar getToolBar() {
        return toolBarPanel.getToolBar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane catalogFilesListScrollPane;
    private javax.swing.JTable catalogFilesListTable;
    // End of variables declaration//GEN-END:variables

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;

        fileService = catalog == null ? null : catalog.getCatalogService(XBCXFileService.class);

        filesModel.setCatalog(catalog);
    }

    public void persist() {
        filesModel.persist();
    }

    public void setPanelPopup(JPopupMenu popupMenu) {
        catalogFilesListTable.setComponentPopupMenu(popupMenu);
    }

    public void addSelectionListener(ListSelectionListener listSelectionListener) {
        catalogFilesListTable.getSelectionModel().addListSelectionListener(listSelectionListener);
    }
}
