/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.editor.xbup.def.gui;

import java.awt.BorderLayout;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;
import org.exbin.auxiliary.binary_data.BinaryData;
import org.exbin.framework.App;
import org.exbin.framework.bined.BinEdDataComponent;
import org.exbin.framework.bined.BinedModule;
import org.exbin.framework.bined.gui.BinEdComponentPanel;
import org.exbin.framework.component.api.action.ActionsProvider;
import org.exbin.framework.component.gui.ToolBarSidePanel;
import org.exbin.framework.editor.xbup.command.BinaryDataWrapperUndoHandler;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.xbup.operation.undo.UndoRedo;

/**
 * Binary data panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class BinaryDataPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(BinaryDataPanel.class);
    private final ToolBarSidePanel toolBarPanel = new ToolBarSidePanel();

    private BinEdDataComponent binaryDataComponent = null;
    private JPopupMenu dataPopupMenu;
    private UndoRedo undoRedo;

    public BinaryDataPanel() {
        initComponents();
        toolBarPanel.setToolBarPosition(ToolBarSidePanel.ToolBarPosition.RIGHT);
    }

    public void setUndoRedo(UndoRedo undoRedo) {
        this.undoRedo = undoRedo;
        if (binaryDataComponent != null) {
            binaryDataComponent.setUndoRedo(new BinaryDataWrapperUndoHandler(undoRedo));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    //
    public void addActions(ActionsProvider actionsProvider) {
        toolBarPanel.addActions(actionsProvider);
    }

    public void setDataPopupMenu(JPopupMenu popupMenu) {
        this.dataPopupMenu = popupMenu;
        if (binaryDataComponent != null) {
            BinEdComponentPanel componentPanel = (BinEdComponentPanel) binaryDataComponent.getComponent();
            componentPanel.setPopupMenu(popupMenu);
        }
    }

    @Nonnull
    public BinEdComponentPanel getComponentPanel() {
        return (BinEdComponentPanel) binaryDataComponent.getComponent();
    }

    public void setDataComponent(BinEdDataComponent binaryDataComponent) {
        if (binaryDataComponent != null) {
            remove(binaryDataComponent.getComponent());
        }
        this.binaryDataComponent = binaryDataComponent;
        toolBarPanel.add(binaryDataComponent.getComponent(), BorderLayout.CENTER);
        toolBarPanel.revalidate();
        toolBarPanel.repaint();
        add(toolBarPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    public void setContentData(BinaryData binaryData) {
        if (binaryDataComponent instanceof BinEdDataComponent) {
            BinEdComponentPanel componentPanel = (BinEdComponentPanel) binaryDataComponent.getComponent();
            componentPanel.setContentData(binaryData);
            return;
        }

        if (binaryDataComponent != null) {
            remove(binaryDataComponent.getComponent());
        }

        BinedModule binedModule = App.getModule(BinedModule.class);
        BinEdComponentPanel componentPanel = new BinEdComponentPanel();
        binaryDataComponent = new BinEdDataComponent(componentPanel);
        componentPanel.getCodeArea().setBorder(BorderFactory.createLoweredBevelBorder());
        binedModule.getFileManager().initDataComponent(binaryDataComponent);

        if (undoRedo != null) {
            binaryDataComponent.setUndoRedo(new BinaryDataWrapperUndoHandler(undoRedo));
        }
        if (dataPopupMenu != null) {
            componentPanel.setPopupMenu(dataPopupMenu);
        }
        componentPanel.setContentData(binaryData);
        toolBarPanel.add(componentPanel, BorderLayout.CENTER);
        toolBarPanel.revalidate();
        toolBarPanel.repaint();
        add(toolBarPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }
}
