/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.xbup.catalog.item.plugin.gui;

import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import org.exbin.framework.xbup.catalog.item.file.gui.CatalogSelectFilePanel;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import org.exbin.framework.api.XBApplication;
import org.exbin.framework.frame.api.FrameModuleApi;
import org.exbin.framework.utils.LanguageUtils;
import org.exbin.framework.utils.WindowUtils;
import org.exbin.framework.utils.gui.DefaultControlPanel;
import org.exbin.framework.utils.handler.DefaultControlHandler;
import org.exbin.xbup.core.catalog.XBACatalog;
import org.exbin.xbup.core.catalog.base.XBCNode;
import org.exbin.xbup.core.catalog.base.XBCXFile;
import org.exbin.xbup.core.catalog.base.XBCXPlugin;

/**
 * Catalog edit plugin panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class CatalogEditNodePluginPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(CatalogEditNodePluginPanel.class);

    private XBApplication application;
    private XBACatalog catalog;

    private XBCXFile file;
    private XBCNode node;
    private XBCXPlugin plugin;

    public CatalogEditNodePluginPanel() {
        initComponents();
    }

    public void setApplication(XBApplication application) {
        this.application = application;
    }

    public void setCatalog(XBACatalog catalog) {
        this.catalog = catalog;
    }

    public void setNode(XBCNode node) {
        this.node = node;
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public XBCXPlugin getPlugin() {
        return plugin;
    }

    public void setPlugin(@Nullable XBCXPlugin plugin) {
        this.plugin = plugin;
        file = plugin == null ? null : plugin.getPluginFile();
        node = file.getNode();
        fileTextField.setText(file == null ? "" : file.getFilename());
    }

    public XBCXFile getFile() {
        return file;
    }

    public void setFile(@Nullable XBCXFile file) {
        this.file = file;
        fileTextField.setText(file == null ? "" : file.getFilename());
    }

    public long getRowEditorsCount() {
        String text = rowEditorsCountTextField.getText();
        return text.isEmpty() ? 0 : Long.valueOf(text);
    }

    public void setRowEditorsCount(long rowEditorsCount) {
        rowEditorsCountTextField.setText(String.valueOf(rowEditorsCount));
    }

    public long getPanelViewersCount() {
        String text = panelViewersCountTextField.getText();
        return text.isEmpty() ? 0 : Long.valueOf(text);
    }

    public void setPanelViewersCount(long panelViewersCount) {
        panelViewersCountTextField.setText(String.valueOf(panelViewersCount));
    }

    public long getPanelEditorsCount() {
        String text = panelEditorsCountTextField.getText();
        return text.isEmpty() ? 0 : Long.valueOf(text);
    }

    public void setPanelEditorsCount(long panelEditorsCount) {
        panelEditorsCountTextField.setText(String.valueOf(panelEditorsCount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileLabel = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        fileSelectButton = new javax.swing.JButton();
        rowEditorsCountLabel_ = new javax.swing.JLabel();
        rowEditorsCountTextField = new javax.swing.JTextField();
        panelViewersCountLabel = new javax.swing.JLabel();
        panelViewersCountTextField = new javax.swing.JTextField();
        panelEditorsCountLabel = new javax.swing.JLabel();
        panelEditorsCountTextField = new javax.swing.JTextField();

        fileLabel.setText("File");

        fileSelectButton.setText("Select...");
        fileSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSelectButtonActionPerformed(evt);
            }
        });

        rowEditorsCountLabel_.setText("Row Editors Count");

        panelViewersCountLabel.setText("Panel Viewers Count");

        panelEditorsCountLabel.setText("Panel Editors Count");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rowEditorsCountTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileSelectButton))
                    .addComponent(panelViewersCountTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelEditorsCountTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileLabel)
                            .addComponent(panelViewersCountLabel)
                            .addComponent(rowEditorsCountLabel_)
                            .addComponent(panelEditorsCountLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileSelectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rowEditorsCountLabel_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rowEditorsCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelViewersCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelViewersCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditorsCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditorsCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSelectButtonActionPerformed
        FrameModuleApi frameModule = application.getModuleRepository().getModuleByInterface(FrameModuleApi.class);
        CatalogSelectFilePanel selectPanel = new CatalogSelectFilePanel();
        selectPanel.setApplication(application);
//        editPanel.setMenuManagement(menuManagement);
        selectPanel.setCatalog(catalog);
        selectPanel.setNode(node);

        DefaultControlPanel controlPanel = new DefaultControlPanel();
        final WindowUtils.DialogWrapper dialog = frameModule.createDialog(selectPanel, controlPanel);
//        WindowUtils.addHeaderPanel(dialog.getWindow(), editPanel.getClass(), editPanel.getResourceBundle());
        controlPanel.setHandler((DefaultControlHandler.ControlActionType actionType) -> {
            if (actionType == DefaultControlHandler.ControlActionType.OK) {
                setFile(selectPanel.getFile().orElse(null));
            }
            dialog.close();
        });
        dialog.showCentered(this);
        dialog.dispose();
    }//GEN-LAST:event_fileSelectButtonActionPerformed

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        WindowUtils.invokeDialog(new CatalogEditNodePluginPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileLabel;
    private javax.swing.JButton fileSelectButton;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JLabel panelEditorsCountLabel;
    private javax.swing.JTextField panelEditorsCountTextField;
    private javax.swing.JLabel panelViewersCountLabel;
    private javax.swing.JTextField panelViewersCountTextField;
    private javax.swing.JLabel rowEditorsCountLabel_;
    private javax.swing.JTextField rowEditorsCountTextField;
    // End of variables declaration//GEN-END:variables

}
