dialog.title=Resize Image
header.title=File Properties
header.description=Properties of the currently opened file
header.icon=/org/exbin/jaguif/editor/picture/resources/icons/48px/transform-scale.png
okButton.text=Resize
cancelButton.text=Cancel
widthLabel.text=Width
heightLabel.text=Height
imageSizePanel.border.title=Resize to
