/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.editor.picture.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import org.exbin.framework.App;
import org.exbin.framework.language.api.LanguageModuleApi;

/**
 * XBPEditor Color Selection panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class ToolColorPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(ToolColorPanel.class);

    public ToolColorPanel() {
        initComponents();
    }

    public Color getToolColor() {
        return toolColorPanel.getBackground();
    }

    public Color getSelectionColor() {
        return selectionColorPanel.getBackground();
    }

    public void setToolColor(Color color) {
        toolColorPanel.setBackground(color);
    }

    public void setSelectionColor(Color color) {
        selectionColorPanel.setBackground(color);
    }

    @Override
    public void setEnabled(boolean b) {
        super.setEnabled(b);
        fillColorSelectButton.setEnabled(b);
        penColorSelectButton.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorChooser = new javax.swing.JColorChooser();
        penColorLabel = new javax.swing.JLabel();
        toolColorPanel = new javax.swing.JPanel();
        penColorSelectButton = new javax.swing.JButton();
        fillcolorLabel = new javax.swing.JLabel();
        selectionColorPanel = new javax.swing.JPanel();
        fillColorSelectButton = new javax.swing.JButton();

        colorChooser.setName("colorChooser"); // NOI18N

        setName("Form"); // NOI18N

        penColorLabel.setText(resourceBundle.getString("penColorLabel.text")); // NOI18N
        penColorLabel.setName("penColorLabel"); // NOI18N

        toolColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolColorPanel.setName("toolColorPanel"); // NOI18N

        javax.swing.GroupLayout toolColorPanelLayout = new javax.swing.GroupLayout(toolColorPanel);
        toolColorPanel.setLayout(toolColorPanelLayout);
        toolColorPanelLayout.setHorizontalGroup(
            toolColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        toolColorPanelLayout.setVerticalGroup(
            toolColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        penColorSelectButton.setText(resourceBundle.getString("penColorSelectButton")); // NOI18N
        penColorSelectButton.setName("penColorSelectButton"); // NOI18N
        penColorSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penColorSelectButtonActionPerformed(evt);
            }
        });

        fillcolorLabel.setText(resourceBundle.getString("fillColorLabel")); // NOI18N
        fillcolorLabel.setName("fillcolorLabel"); // NOI18N

        selectionColorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selectionColorPanel.setName("selectionColorPanel"); // NOI18N

        javax.swing.GroupLayout selectionColorPanelLayout = new javax.swing.GroupLayout(selectionColorPanel);
        selectionColorPanel.setLayout(selectionColorPanelLayout);
        selectionColorPanelLayout.setHorizontalGroup(
            selectionColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        selectionColorPanelLayout.setVerticalGroup(
            selectionColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        fillColorSelectButton.setText(resourceBundle.getString("fillColorSelectButton")); // NOI18N
        fillColorSelectButton.setName("fillColorSelectButton"); // NOI18N
        fillColorSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorSelectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toolColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectionColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penColorSelectButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fillColorSelectButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penColorLabel)
                            .addComponent(fillcolorLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(penColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toolColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(penColorSelectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillcolorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fillColorSelectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void penColorSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penColorSelectButtonActionPerformed
        colorChooser.setColor(toolColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, "Select color", true, colorChooser, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setToolColor(colorChooser.getColor());
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_penColorSelectButtonActionPerformed

    private void fillColorSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorSelectButtonActionPerformed
        colorChooser.setColor(selectionColorPanel.getBackground());
        JDialog dialog = JColorChooser.createDialog(this, "Select color", true, colorChooser, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                setSelectionColor(colorChooser.getColor());
            }
        }, null);
        dialog.setVisible(true);
    }//GEN-LAST:event_fillColorSelectButtonActionPerformed

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JButton fillColorSelectButton;
    private javax.swing.JLabel fillcolorLabel;
    private javax.swing.JLabel penColorLabel;
    private javax.swing.JButton penColorSelectButton;
    private javax.swing.JPanel selectionColorPanel;
    private javax.swing.JPanel toolColorPanel;
    // End of variables declaration//GEN-END:variables

}
