/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.xbup.jaguif.viewer.def.gui;

import java.awt.BorderLayout;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.BorderFactory;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;
import org.exbin.auxiliary.binary_data.BinaryData;
import org.exbin.jaguif.App;
import org.exbin.bined.jaguif.component.BinEdDataComponent;
import org.exbin.bined.jaguif.document.BinedDocumentModule;
import org.exbin.bined.jaguif.component.gui.BinEdComponentPanel;
import org.exbin.jaguif.component.gui.ToolBarSidePanel;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.xbup.operation.undo.UndoRedo;

/**
 * Binary data panel.
 */
@ParametersAreNonnullByDefault
public class BinaryDataPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(BinaryDataPanel.class);
    private final ToolBarSidePanel toolBarPanel = new ToolBarSidePanel();

    private BinEdComponentPanel componentPanel = null;
    private JPopupMenu dataPopupMenu;
    private UndoRedo undoRedo;

    public BinaryDataPanel() {
        initComponents();
        toolBarPanel.setToolBarPosition(ToolBarSidePanel.ToolBarPosition.RIGHT);
    }

    public void setUndoRedo(UndoRedo undoRedo) {
        this.undoRedo = undoRedo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    //
    @Nonnull
    public JToolBar getSideToolBar() {
        return toolBarPanel.getToolBar();
    }

    public void setDataPopupMenu(JPopupMenu popupMenu) {
        this.dataPopupMenu = popupMenu;
        if (componentPanel != null) {
            componentPanel.setPopupMenu(popupMenu);
        }
    }

    @Nonnull
    public BinEdComponentPanel getComponentPanel() {
        return componentPanel;
    }

    public void setDataComponent(BinEdComponentPanel binaryDataComponentPanel) {
        if (componentPanel != null) {
            remove(componentPanel);
        }
        componentPanel = binaryDataComponentPanel;
        toolBarPanel.add(componentPanel, BorderLayout.CENTER);
        toolBarPanel.revalidate();
        toolBarPanel.repaint();
        add(toolBarPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    public void setContentData(BinaryData binaryData) {
        if (componentPanel instanceof BinEdComponentPanel) {
            ((BinEdComponentPanel) componentPanel).setContentData(binaryData);
            return;
        }

        if (componentPanel != null) {
            remove(componentPanel);
        }

        BinedDocumentModule binedDocumentModule = App.getModule(BinedDocumentModule.class);
        componentPanel = new BinEdComponentPanel();
        BinEdDataComponent dataComponent = new BinEdDataComponent(componentPanel);
        componentPanel.getCodeArea().setBorder(BorderFactory.createLoweredBevelBorder());
        binedDocumentModule.getFileManager().initDataComponent(dataComponent);

        if (dataPopupMenu != null) {
            componentPanel.setPopupMenu(dataPopupMenu);
        }
        componentPanel.setContentData(binaryData);
        toolBarPanel.add(componentPanel, BorderLayout.CENTER);
        toolBarPanel.revalidate();
        toolBarPanel.repaint();
        add(toolBarPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }
}
