/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.viewer.xbup.viewer.gui;

import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.JComponent;
import javax.swing.JToggleButton;
import org.exbin.framework.utils.TestApplication;
import org.exbin.framework.utils.WindowUtils;

/**
 * Document viewer panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class DocumentViewerPanel extends javax.swing.JPanel {

    private final List<ViewRecord> viewRecords = new ArrayList<>();
    private int activeView = 0;
    private JComponent borderComponent = null;
    private String preferredView = null;
    private boolean updateMode = false;

    public DocumentViewerPanel() {
        initComponents();
        init();
    }

    private void init() {
        modeComboBox.addItemListener((ItemEvent e) -> {
            int selectedIndex = modeComboBox.getSelectedIndex();
            if (selectedIndex >= 0) {
                switchTo(selectedIndex);
                if (!updateMode) {
                    preferredView = viewRecords.get(selectedIndex).name;
                }
            }
        });
    }

    private void switchTo(int index) {
        if (activeView >= 0 && activeView < viewRecords.size()) {
            ViewRecord prevRecord = viewRecords.get(activeView);
            prevRecord.button.setSelected(false);
            remove(prevRecord.component);
        }
        ViewRecord record = viewRecords.get(index);
        record.button.setSelected(true);
        add(record.component, BorderLayout.CENTER);
        activeView = index;
        revalidate();
        repaint();
    }

    public void addView(String name, JComponent component) {
        if (viewRecords.isEmpty()) {
            add(component, BorderLayout.CENTER);

            if (borderComponent != null) {
                remove(borderComponent);
            }
        }

        ViewRecord record = new ViewRecord(name, component);
        final int index = viewRecords.size();
        viewRecords.add(record);
        record.button = new JToggleButton(name);
        record.button.setSelected(index == 0);
        record.button.addActionListener((e) -> {
            switchTo(index);
            preferredView = viewRecords.get(index).name;
        });
        modeComboBox.addItem(name);
        selectionPanel.add(record.button);
    }

    public void viewsAdded() {
        int viewsCount = viewRecords.size();
        if (preferredView != null) {
            for (int i = 0; i < viewsCount; i++) {
                ViewRecord viewRecord = viewRecords.get(i);
                if (viewRecord.name.equals(preferredView)) {
                    switchTo(i);
                }
            }
        }

        if (viewsCount > 0) {
            modeComboBox.setEnabled(true);
        }

        updateMode = false;
    }

    public void removeAllViews() {
        if (!viewRecords.isEmpty()) {
            if (activeView >= 0 && activeView < viewRecords.size()) {
                ViewRecord prevRecord = viewRecords.get(activeView);
                remove(prevRecord.component);
            }
            modeComboBox.removeAllItems();
            modeComboBox.setEnabled(false);
            selectionPanel.removeAll();
            viewRecords.clear();

            if (borderComponent != null) {
                add(borderComponent, BorderLayout.CENTER);
            }

            revalidate();
            repaint();
        }

        updateMode = true;
    }

    public void setBorderComponent(JComponent component) {
        if (borderComponent != null) {
            remove(borderComponent);
        }
        add(component, BorderLayout.CENTER);
        borderComponent = component;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        selectionPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        modeComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Button.shadow")));
        headerPanel.setLayout(new java.awt.BorderLayout());

        selectionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        headerPanel.add(selectionPanel, java.awt.BorderLayout.CENTER);

        controlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        modeComboBox.setEnabled(false);
        modeComboBox.setFocusable(false);
        controlPanel.add(modeComboBox);

        headerPanel.add(controlPanel, java.awt.BorderLayout.EAST);

        add(headerPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        TestApplication.run(() -> WindowUtils.invokeWindow(new DocumentViewerPanel()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JComboBox<String> modeComboBox;
    private javax.swing.JPanel selectionPanel;
    // End of variables declaration//GEN-END:variables

    @ParametersAreNonnullByDefault
    private static final class ViewRecord {

        String name;
        JToggleButton button;
        JComponent component;

        public ViewRecord(String name, JComponent component) {
            this.name = name;
            this.component = component;
        }
    }
}
